import { AuthAction, withAuthUser } from 'next-firebase-auth'
import Head from 'next/head'
import FullPageLoader from '../components/FullPageLoader'
function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
      </Head>
    </div>
  )
}


export default Home
