import Head from 'next/head'
import { useContext } from 'react'
import FullPageLoader from '../components/FullPageLoader'
import Login from '../components/Login'
import { ContextProvider } from '../utils/context'



function Home() {

  const {userIsLoading} = useContext(ContextProvider)
          
      return (
        userIsLoading ? <FullPageLoader/> : 
        <>
            <Head>
              <title>WorkFlow</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Login />
        </>
  )
}

Home.getLayout = true;


export default Home